version: 2.1

jobs:
  build-frontend:
    working_directory: ~/repo/ml-webapp
    docker:
      - image: circleci/node:17
    steps:
      - checkout:
          path: ~/repo/ml-webapp
      - run: cd /ml-webapp && npm install
workflows:
  version: 2
  build:
    jobs:
      - build-frontend:
          filters:
            branches:
              only: master